[tool.poetry]
name = "nvim-python-provider"
version = "0.1.0"
description = "poetry virtual environment for nvim"
authors = ["DannyDannyDanny <dth@taiga.ai>"]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
