on:
  push:
    branches:
      - main

jobs:
  install_codespaces_setup:
    name: install codespaces setup
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
      - uses: actions/checkout@v1
      - name: install script
      - run: ls -la && bash install.sh
