on:
  workflow_dispatch:

jobs:
  manual_worflow:
    name: manual workflow
    runs-on: ubuntu-20.04
    steps:
      - name: Run `lsb_release -a`
        run: lsb_release -a
      - name: Run `apt policy fish`
        run: apt policy fish
      - name: Run `cat /etc/os-release`
        run: cat /etc/os-release
