on:
  push:
    paths: install_tmux.sh

jobs:
  install_tmux:
    name: install tmux
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: bash install_tmux.sh
      - run: tmux -V
