on:
  push:
    paths:
      - install.sh
      - install_tmux.sh
      - install_nvim.sh
      - install_fzf.sh
      - install_fish.sh

jobs:
  install_codespaces_setup:
    name: install codespaces setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: bash install.sh
      - run: tmux -V
      - run: nvim --version
      - run: fzf --version
      - run: fish --version
