on:
  push:
    paths: install_nvim.sh

jobs:
  install_nvim:
    name: install nvim
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - run: bash install_nvim.sh
      - run: nvim --version
